### PR TITLE
Sonarr: avoid downgrade on package updates

### PR DESCRIPTION
**Pull request by mreid-tt**
## Description

This is an attempt to incorporate the changes in https://github.com/SynoCommunity/spksrc/pull/5485 adapted to Sonarr to address the comments raised in https://github.com/SynoCommunity/spksrc/pull/5471#issuecomment-1317381973.

Fixes # https://github.com/SynoCommunity/spksrc/pull/5471

### Type of change

- [ ] Bug fix
- [ ] New Package
- [x] Package update
- [ ] Includes small framework changes
- [ ] This change requires a documentation update (e.g. Wiki)

### CODE REVIEW

**Comment by mreid-tt** [comment]
@Seanstoppable, any thoughts on this PR?

**Review by Seanstoppable — APPROVED** [review]

**Comment by Seanstoppable** [comment]
Thanks!

**Comment by mreid-tt** [comment]
You're welcome. Hopefully this can be pushed to your PR and get approved for merging soon.

EDIT: I just took a quick look at the PR and I seem to have made an error transcribing this line:
https://github.com/Seanstoppable/spksrc/blob/4a6fd649e1a0fbc1cde9014d9973c119bb4f83f3/spk/sonarr/src/service-setup.sh#L110

It seems to be still pointing to Lidarr from when I did the copy and paste. In your review please be sure to correct. Sorry about that @Seanstoppable

**Comment by Seanstoppable** [comment]
Ohhh. Just realized this was against master and not the branch that powers my PR. My bad. Saw your new PR and hopefully that will move forward

**Pull request merged**
